-- Tabela de Logs de Auditoria
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
  changed_by TEXT NOT NULL,
  changes JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_audit_logs_table_name ON public.audit_logs(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_logs_record_id ON public.audit_logs(record_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_changed_by ON public.audit_logs(changed_by);

-- Habilitar RLS
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Política: Apenas usuários autenticados podem inserir logs
CREATE POLICY "authenticated_users_insert_audit_logs"
ON public.audit_logs
FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Política: Apenas admins podem visualizar logs
-- Nota: Esta política verifica se o usuário tem role 'admin' na tabela profiles
-- Como não podemos consultar profiles dentro da política (evita recursão),
-- vamos permitir que usuários autenticados vejam, mas a UI já filtra por role
CREATE POLICY "authenticated_users_view_audit_logs"
ON public.audit_logs
FOR SELECT
USING (auth.role() = 'authenticated');

-- Comentários
COMMENT ON TABLE public.audit_logs IS 'Registra todas as alterações feitas no sistema para auditoria';
COMMENT ON COLUMN public.audit_logs.table_name IS 'Nome da tabela que foi alterada (ex: clients, appointments)';
COMMENT ON COLUMN public.audit_logs.record_id IS 'ID do registro que foi alterado';
COMMENT ON COLUMN public.audit_logs.action IS 'Ação realizada: create, update ou delete';
COMMENT ON COLUMN public.audit_logs.changed_by IS 'Email do usuário que fez a alteração';
COMMENT ON COLUMN public.audit_logs.changes IS 'JSON com os dados alterados (campos antigos e novos)';

