-- Tabela de Tipos de Serviço
CREATE TABLE public.service_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  valor_padrao DECIMAL(10,2) DEFAULT 0,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.service_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso público total a service_types" 
ON public.service_types 
FOR ALL 
USING (true)
WITH CHECK (true);

-- Tabela de Produtos do Sistema
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso público total a products" 
ON public.products 
FOR ALL 
USING (true)
WITH CHECK (true);

-- Tabela de Configurações do Sistema
CREATE TABLE public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave TEXT NOT NULL UNIQUE,
  valor TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso público total a settings" 
ON public.settings 
FOR ALL 
USING (true)
WITH CHECK (true);

-- Tabela de Bloqueios de Agenda
CREATE TABLE public.schedule_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  hora_inicio TIME,
  hora_fim TIME,
  tipo TEXT NOT NULL DEFAULT 'geral', -- 'geral' ou 'funcionario'
  funcionario_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.schedule_blocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso público total a schedule_blocks" 
ON public.schedule_blocks 
FOR ALL 
USING (true)
WITH CHECK (true);

-- Adicionar coluna valor aos appointments
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS valor DECIMAL(10,2) DEFAULT 0;

-- Inserir configurações padrão
INSERT INTO public.settings (chave, valor) VALUES
  ('hora_inicio', '08:00'),
  ('hora_fim', '18:00'),
  ('almoco_inicio', '12:00'),
  ('almoco_fim', '13:00'),
  ('dias_funcionamento', '["Segunda","Terça","Quarta","Quinta","Sexta"]')
ON CONFLICT (chave) DO NOTHING;